### ISSUE TITLE
Гитхаб, изучение: Fetch, Подтягивание  информации об изменении (5min)

### ISSUE THREAD

**Issue by rudrastyh** [rudrastyh/app#2]
Роман, ну я делаю Fetch, но ты запуш что-нибудь )

**Comment by roman-bandurin** [comment]
запушил
Миша, перетаскивай листок в проекте на меня, а то непонятно, что мне что то адресовано. Я сделаю свою часть и перетащу листок на тебя потом - и ты узнаешь, что снова тебе надо что то делать

**Comment by rudrastyh** [comment]
всё, разобрался с push и pull )) отлично!
